apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-creds
  namespace: nextcloud
spec:
  encryptedData:
    password: AgC6mozf++LkYMj19tA7asDIASNkIno4HnEvB1uAHkwtg162k0Ga07qVVbmPhs7cw55dvbN/oH6qXWHyFKO/v4NXlLOrpR4/XqO3syiCGvVgR38j4aVtBJ7Evlg4C/4eNr29/OIhvce3jJS9+zlXlLhU/rn2eJtbsA2AbiQkDqbIbBkrAmjYo4K9pvH/yKXJHz6NC84Ms4hMZ8AvvdafTC2b1gOYsrqwk4/8ogzaRzuCI8f7VtWubteyi4kUoxNwRF4jXvukx3jMcZON2gbUi2UeGs01C+RJJNI5tXn0bVYm44shMsKJEvwSFp0x/JGRIkjT+2eYnABLQDa0usKSwyYiqc45zQG59KsiB4lig8XM+c8SfZ3u7/od4rGDkTUTQ+/5048pvLyqtFyMUIRyxeidU5B0PUYbxxy6MSkLX1nsfsuNRUTfPc+NZez3Rj58877TMsiI+7GQpcNCKsGP43qGhnO/1+fdDDSZ86rI2DAVsrrGlbWPPYvqJxdTjJbeheUi6Lsd/4xLF419wLWDnRGSUTzTs6jy8mPA6PTjtlOmi3pinzGn8yLRVEMYYTzY4DgNbytn2a4HIDEnr4Rjs4lZVRBfsF0IPVhuC58QEvl0oB2kMnqvApI8Lzg9DDg7hyXw5qa683MzDDkT+jcSkZ7ke8CzefY72OmoVUY1ctbOScl1Ds8D4fjCJrhdMJQb0IauTUJPUEx2ciaBzVzcTP1saevVC38x74EPoCs=
    username: AgBiCPlMDuskO3hCvXbDGXGwRW00U/iDOJo+ojuDcC4tJgKZc7f/NBuNxgr/ORY6SAgqRO26AJ9Yi28MUY777mYqQilDIo5MjNwLNsW5DH/uIq34ixcAOXAuYihetK25COiF5m80Ek373BMwobIvE5nH9csNfiLNNu79f737CQYJkEqO5xUOU49MPBqLiBuV+zjY2sGEzbmNMRIIKyF7ul3Zoxqf9dW8/2AqJkO4E3tt2e9VxKXfE5WR2ItLF8m9yetG8FbgzJ0DTj2fMKOgJTK84sNqe7gnC3ENbeFUdPX8Sv3GuLAnOdsVQRg0JtEstVfiPbDzJhmXYWzddCxXNKU5920ABqhaZVUk2mG1T+gOQ+phVC2ufI5M3iEyhadMprjTBHEkZNfwQIWudShTYjifNnKtpjbS/85fr52ZN5bvvsxh5Y6Y901LOeEKXylM7BhbCXbNtqoJNKZqsv9ceWgYPZgRWOppOLg64Ud1lH8jJTALnraXT+hoD896jpV/s0mN8E/hmKgQxhsh/i6m+1mRkdRH09qjcD9T9mAu3ybbz+a5UjJplpxsbJ0pu+En/rRv5ud9uow7i5uJeyqpU4K35CYxVipyXNgFJiO+5PoPuLgxdj0/lzbmPjR457BAri8lyQv3l5RFkoti0SvTP/ES1tXTGh/3n21YLmYpEdMK1dBh3mUShFLTiRoUJsRsku6KCL+pxw==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-creds
      namespace: nextcloud

