apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: bookorbit
spec:
  target:
    service: bookorbit
    port: 3000
  rules:
    - hosts:
        - bookorbit.int.imdevinc.com
  scalingMetric:
    concurrency:
      targetValue: 10000