apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spellcards
resources:
  - namespace.yaml
  - sealed.yaml
  - service.yaml
images:
  - name: ghcr.io/imdevinc/spellcards
    newTag: 0.1.0
