apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: btc-tracker
spec:
  target:
    service: btc-tracker
    port: 3000
  rules:
    - hosts:
        - btc.int.imdevinc.com
  scalingMetric:
    concurrency:
      targetValue: 10000