apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    service: btc-tracker
  namespace: btc-tracker
  annotations:
    k8up.io/backup: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
