apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  queue.yaml: |
    organization: imdevinc

    repositories:
      - imdevinc/fifa-bot
      - imdevinc/pr-queue

    ignored_authors: []
