apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - deployment.yaml
  - sealed.yaml
  - service.yaml
replicas:
  - name: pr-queue
    count: 1
namespace: pr-queue
images:
  - name: ghcr.io/imdevinc/pr-queue
    newTag: 0.0.10
