---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: creds
  namespace: umami
spec:
  encryptedData:
    APP_SECRET: AgAriqhq6P3lrNvcET2E/TfxSPFI07NN568M+gzf3g9r+1xrCon01kRPCHR4bXhrEPLolvatkob/noL/aRpi+/IX4DnzSDoh+TYnQGpmsxFC4FrYs60eeYCEB+Fg+sOUqlhQLpVZ2FeQmvBQsAWRP1BadLVF2MxqeRsNpFNidSFBCt71lKRL1cHZ/UwN+fYBV308kC63u4RvwgEjzsgVZhnxpJD33MlsDkcA4Ntv5WXacjssGb8YA9HXagVQyIsZH9hXhtKy2I84K0MRIM2j7/EfpNRUbD7SBzqJtG8+2e8lLn/vs3/lEzNcQjcyeqAUztzXBPRZaAVT+/fR2wqxVsaVPhw40Joa+kk7d+LcWMi4sce/RqlSgrgcVq0adxv1qqk697NheEH6AcptzfnENi91kL+uIhcOnAKBi4YPzVy+51bN1MLUdgNgK4viYJ91r3KXQWA/oc6Kb3rP+O2jJuyoOKH02epy2gRWAbmWIlnOoGg6QO5PxhzKfDrYHm/24XJGsXilrmFZ5RUNelQ2yG0w3Y5H890Kppfn9dkFcc0gcA/7cOAFsMuIS004mJbeBZsso2RHgoym7i7Y2oPTkJBtkyEsjZP8Mt5SX6rh69+C17CQFv2lRpKXfW/LaE58STQJKOzvJ7utJ84xEIJkDUyamMHCgY8aCnFETDKteg3ehQGPi9q+7e1VNa5Fa1VGYzJLQoFjcHM88KXc1lrCpECVbMV122qBlnL/
    DATABASE_URL: AgBbXTf3hSdC4N30SVIGVHhMW63KJOTpY4I7HsnxCSGxfMgP0s6FS0A1SEh2F+AbdteYqcIOobixS3z05IkeV8FtEJ45LO/K2AbKgx7jWFYCmpWjaZHUG2Y2P5NECrihKwBlvZMeCU4eZ1bAfr1gghP5Pr8w25ycNWXJyn8z8tyflFjH2NxcGecUqfXPKeb2XM7r9XmCRCGpJqh12jda1dSodurmT61HDzlQqNKmunW53L0Fw7cUFFGmTWKr8p5Z42gF0Q3dHOfyTHDHGKFReV+2iOSHTSJZoo6dlwcIF1X3nA26+ZoUDfOpox1nfAdUKc1RUb9jpm3g4bVeFAsFCK7+QiU2ZV91lKACgGJzJDpwPAYYJefy4qE194DWg1+cqxjfBFoUT7CWSkex/yNQW/0S3d4Q0Bh0X1gMiMFTymJEAHoImqxJ6FfirIbkk36vZbD/NR9VhF8bcH8b9bEAv3bx9PAEd16Cr+rK/XfasdRZzsjjYCeucR238n3oT06fSbEz2LkHQ8x5d+8EymMRdLCbKl6Plge47JmueAyL7sdqGMb+DEgaHYq0SCUc92B2b/I4SLxPexEj/t00vlLTTBGDu5sJ9CYlzbtG9DBp/8CKFHg2GQ9CmwU304NqnodTEMcQsSwGlxUoj247mo250QILei4U3Udzefx41793e7Xl8czD2JkAOKkyVZmrWGaqI4TBu/vrXiqA3BKdI1/V75ohFp4qR3U/sBMvP1oxckUljOhdSOponLpwLQA0zHZMfz8uev9jV5OfgJdzus0G+4TunhgL5kH2dq7uNFUzA0kKnsTw0YtrWxtjRuqO7Xc=
  template:
    metadata:
      name: creds
      namespace: umami
    type: Opaque
