---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  encryptedData:
    password: AgAW1IQ5KHXNrLTA7Ri3kIkRep2570IcWcjted5jRQSbizRn6Qexo+Nkna+nr/3T440mnV7XWTO6cjbXDwGJcj8FupstzaZrO+uXp6siQLpEGGLCFvSG0Fuqu3928hDwbqi16viqsUffx+hb1/Ma/k3XzNnxhH7Z1KaWN8u5JJk0L+CoSjmXZXX6W/UqFwRFYV85cz1iqGz7eH1607QS+VzgzeXF8b5GtYufVQRA2aGtQ39G7Q6APBcquoqISKL1IpAkOyB1YOBgPBw1PeJxeYvPcY74o3ws9o6DYb2EUTZWS+g3fy8xwbdRbrrtLj4ADqbCfI+lAmxchgBmtwwOjScFXJR1C/P3KG9a0jddl/Zv+wc8SzH4WVVQkcKyez5L2encWrzHwvJcnJvWlQUc2tXeK42ko3+Sx+cbODnK/8XXhB8y0H8UvSKnC/uHFHPJbcHUe+PeToxKdoit3xr6SDc2Wkab+BEDEnu88xzXQeLVUWxd2tQaOhKl+YwhK9bZygDncUzKzwUD6alCPcD5V5ALZr5hsDlquiuMuhN7cyqYRwW9ykdTUpJRMr3+8vXILPEF4WfUxZcBbr+Y4cxaV2Dm43VOCsAB8jzbtD4Xwpz/aPO3pxi+qXjzSMP6/sblPNyyCLP7OqMBI4D4L1gFAC6VjGdqo3iUb8EarE3i0OOyazWLuSdlMJ+YRi/De2PoYmnn3GJFsMevm8sP0XbObdxWzk1zIQHq
    username: AgCiD5wQLOXjLIeL6bLLpfLhM02P54XyIDs19YIT0ysLRpQVXL8CMrrqqiJ/kTKVvVtMWQAq23X6WQI2+lVAlNCzmrLlhw0vmLP79YfJy1YkNvuaQ7EZlt+lb69iaoumx0Z3H7GD1YDP3w6mzNqFtSf2ueglKiV5PZhz2W6qaIJCupBuLC8OuTVgP/9kX2/dHXCazG0kl13VhcT0Uzs9yuteb8UM2LMni8ZUhGMBQ93XDpTym9wg8QF9MfZPv3sfDqoJ6Cm5NQ7oNcNxtt1Wpf9i6MH5dEpqy11Ajz5GEjV4MMt7Jeumst/tlwLqbo/Ubi724fIuk366rK3vlrLZWwVNkjEb87MAnC9pur03tKCLR7rc25kEC0xOFdNf7xOySRwYh+0b6bAjXEsnl/OOUtzu8MX4FDy4dbxQQLeZ6bA83hqoapEPOn3y2fBIec8GUqSzEfNngKSRGIRWLUk0hMdqfr+qywxSN2qyZENTlxa6LXRDyQA8LhLg47n21mwsDMy3nGOgAZ84wwHWOFXrWz0Gmz7zpzFSni1VH8TD2YWCeYb/wNLVjtt76IVlvVjcLD2TMq+vyoJYVdly/+kiTCT0BhfSI3SdUjKcvFUMryXZIcw8buu4K2k2yqNbj/BitcJ2YN9TpUhdmyPGFScMLpqYy6r46+LkaUT6sZmeVW1u6rnAP/TsdZFzgK91Pp5tqrv/d9bUCuxporDVJzA=
  template:
    metadata:
      name: forgejo-admin
      namespace: forgejo
