apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: forgejo
    releaseName: forgejo
    namespace: forgejo
    repo: oci://code.forgejo.org/forgejo-helm
    version: 17.0.1
    valuesFile: values.yaml
namespace: forgejo
resources:
  - admin-sealed.yaml
  - oauth-sealed.yaml
  - namespace.yaml
  - tcproute.yaml
