---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-oauth
  namespace: forgejo
spec:
  encryptedData:
    key: AgBv7uYltyceu8molvq0nWcm8UTy91aWzWgxCDCaMES5TKNJN1rY1TbhlFX/XhQQ2wd7u1EdunBqU4uifHHzJt+DDnHhPOaWJST7UaXlKj2q51LkcRBti3ctTzC6QSxyd586r1XpPLnYCw/8N9vozbGO7hZxTOvIBU0gt3RUEg9M8y/6JIPU07hMt9JNla6ckSceH1CwhaNuV/EjW1M4/rRxT3PMCm5QGJzMHTIQVKthei7sBJPqnbHG28EYpCtnJ5JWq/nCmE1A+MXavPIywR8PqEzNdSwKx2MkARAiLS786CwcOP4lWNMi83Fp32Ja02XPSb6GsShO4R1auyB7b0g0TQF+l24YUt9e08ObPaM1GR6hR6x1UA35Fsv5YXdp77ygonuSyY+cFxbCB1JBwbzwr2ChQQwwWtO7zlukjjtLjoQLYzk5Btqw1dM77J7Q6rpMDODnU12ImyT9KOlwpCEpOR8bGvkYN0e+4Tkia7Jd0uAwU8YOMULevWi4rwbPqgW0+N70DgvNE9rywCt42ijfcw+m1HTOyfv9fM4a3L+Mbl2ks8K5Ere0HQGuoAgAv2w94MH0gLlOf6hGau41eMHzhFPxySe8wAvTAPb26Fp+Sqtnhvct64Wq5Ao8LdCyCc7d0OqeQm5V570pjelGj4yAMxFlx3xmrMH0x60Kdyy+GFCGGr8NID6waJV6VnGFK9Az3lnHdwgvdQn2BBwfDlVBgg7VYtbBZQ97kpF4+FxOzHFgWVk=
    secret: AgCZKxOQuDXEteTnpHZDlPHmWgdGaZBzEwC/tGtLa+Bc1DM901KNc50p8FBCk3GydouIJ4ojLtMtr8omnbCiwlf5FRKkQ4pjwvd9d9P6iqK63klNtU/YT2e5RxwdB1XjiUCeyDakqeAccEbFQJcwtVYX8q47PFuozG1/DwtHHnOQqC0QgM2XL0SenoVlL4jS/cegjmuE3Cr/OfD2BzpbR9AV7OwCEXr2vZXINMJd8fblq+XmZIxcLUD3oLkTpvRv6svpUczyucipBp1faD0SOQ8iiLprDeFa0DUkPAjIO4xENkuYhwKrQwVelsn7akpwMmTEYEvoEhDGP6hMW/9QY0lkY4OUnWSEzp4LzeXZovkvMDOqB4EmtqvabjxJGU0wTWKwowK6B7x3BxXUihnT5ILk09scn4nSxOlCciXGC6ZiJpQ68IdSpjXMPYdfIsvCwKSC/MLPZuB/ivsRV9ObnjHr63n6i01bpVnbdRabmvqhuhB5udHANntFGIsXLKRB2Erd0kk+5CAvuVl/wjmQLRcEG4f34KO838lGw+jhjFMJGl0jor1rShYAWat2J5QCgAp498A5yI2jiPLggJ5fa/vWQNOprL07RNygvkPh+4BnU/DVaZSQeHve6hIsAeAQ5PqiDI0Ub7rFDuvFuC8rVSdLt7F4X4xQ6X+i1gU5F22AwXveeEpgqs9zaJESS/Jq3zqzgF/u76m9BGwHYjDHNoPd+hEhwUJ+SjwoR/8hcw/HOw==
  template:
    metadata:
      name: forgejo-oauth
      namespace: forgejo
