---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-oauth
  namespace: forgejo
spec:
  encryptedData:
    key: AgBOfMp2WuhQqypb0ymjHuvjV4lPQpTk0Vo1ns50i8l2q7+Uz4EtZMZmgNw1sITefLeCwZrvcLxufAohI0jTNC4kGWbA4t1Bc91KsrMaGAaB8oEgTLL/y9PP0HpJQm875iFJ13NMvSjBuZFgCp0YpmcsTO1ETIpo035y99jsIxMJNl3YXBAhrtHMUKRBQ91shSpIXtLWeocEKI8fWb8oudDPXb6uTcMFAJIjJiRvJN/TtoMZfYphlBpvshiK1aiBVUyYeCXzfLnKF2i+1QFwlUyoMZSWenQGWFms2xvSm+JlYMtl6H9HAgGhENNklqgtn9b1Fe2De14XurME+qemjxSSORhuDrbcnr8M3jS2L7SWdfZt7vXjyLZGCIJoO659imUlseXADjZ61PhavZksFQp+RWC2OdCDVYM7i3uepZH7YxxQkagA8aQJPaZ0qXjaK+yLaMunMQgFQQVCuBuoeiCeAB7riBN/KNXygp1Yu+yOw029goMqbp1VDvqz5WCjo3oSEa+FYL0gJhGSBK4VBaXcYo3tTpeldRd+bH5fO65U1orR6xyHdeOtofnRc45Rc5MGylDREImFyvC4Y19yw7RAicm6tVwLoPYwroewQr+NRlP/1cxUMroMGLYoTaV+sZ3DkpjfQICbW7m1d/GA7UnMGshZR0b/q6UoncUlbioFG6mLiEZYk6I6ireoZ7xaayl12irf37mMlP3QjDUIIho1aawlAss0A/CxyRQ6z/KFb2KXbWI=
    secret: AgAPVRRovM+jZa9ZwVhBG5+VuPbLYf8swqGTtHfKNoSiXEVNaXDGGv+CN6AnK8BxbXY4Ej+fvMyj77PaKTBAYrRgkb6IVAsERv9FDSt14SqFKNQztOk72E7c3fLPJr2Drdww4sg+qD7lPSoS65hdGwM0fy0DutnwGG1OfYemlq1ZKQlS0DxRQtManf3CNhMmbE6XRZfCgwU4Cj/xzwToxdTKiHk4boBzfG7hZlIxe0tOFAxOmd6hCCzOwAwqvKP9D3BAY1N3t91N+O5+wMQNCNIC18P5/D3+XTlmqvbV2ADMDPNB+ZnM1LvS/q2TzOkllYQdBDA1EhEpuSYWdNHCE4A8NDN4hKDfBK8NDhS8eyrQvQyJ3D4S0f8Z7DfxCqeBt6Nqg/GUcXgIPRWgFGIoEwSkg+/1GIWK5z6KhawcOUUjks8zhrGFVHARdZVQlWoe1pvnKWjDD99L5s/7HJBLm2C1qhEOZwCptpHRmW5lL/IhAimEDM67F5JiecCg+FjUYrcmnukRs3IkIRMt4pktvHj+5dblMBoHFfUwtQbXQVLZ+LvVLzz4t9TW8nJXrzmZpdE2hpdNj5/nfcTaxJHrXAJr0MURV7vafzmSCLUI0yqWr80Z1WFInvdg/MTJ+lvrB9b3HBXQjIO0yzMykvxDg5kIsrwg3ps9o5mtPt3xMlubQkfUN0QQoA0eNx8Km9ZPjrGrS6yhwTrCJPWTp987QkA2Z6YnvBfxr5dPW0ehMv5LmQ==
  template:
    metadata:
      name: forgejo-oauth
      namespace: forgejo
