---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-ssh
  namespace: forgejo
spec:
  encryptedData:
    privateKey: AgC6nsd1VCgMXo94P7ORR4xzeH9u+Re/cbJShRAVONSs0yptrQUs6MBE35RubUK3rGOHRk0d0pmZLX6AfD3YgzdhaWS66R1B4C02FanNiupetpnXeH9VYHJMtQUWN2qx35TwU/1tziM0or/1L0QL1n5lAqRP8GERVsfh7kPugXZnl0iUBk9oWxnzEz+D7LSCd+1rhSpT28memBiTJ/0pa2dyxyiYEvowoCrFp6G5WeG0QKMpzmcYhe0ZYNQuo1Cs/TRXl7RtYC/Ifsn7H9UjfPQkYME2bpDPNu9MFTMaEtDNQqsEo7CRUqrHqQN1ERd98isE8w8BaGm+DXs/sA8zMb2LCwDO/GA0Hb7p6tNWYILqqiTYKhwlqgSPMHjaK1RpkGv+Bd2jg9AptNc+nBCIiXQ27ZLGaKxRdQ3i1sLGI2Uc30hcivkBiIUYKu+Re5GGKCxiA87cmWz2K+fm5kAIOabfVKkQCVCBfUdvrLYDT473oD+jqph8vjIs5LIZrTO760sVviJ/LQSSWCYoVUaT1AfOqmuyKEuknq3cF0u9JRKb/8ENtnUBxdY0yGdm0Gczc9SEy7MZmQKamuMBoZDQs/Sk8yysQ9PkipmUM6EcjDvB63oSHUNG/wrZ9wIZedAN5j3BCkwvbZ0J76H/P3jZ+t+i/2i9df20tkAQ/wYFWL9m6v4Q3p15ml0Pr1kXhslzgLZ+TsHbspcE1Pp/4LjVyWVQWkok5OFwFYgUhSPMfdgeqSHdmEswKEL+rjYXiA8qocenoPW/tlZVeJb5Z+0wjwY1W8i7620xXKQpWPqS0BoI6hLA8oLH6FJldxsE30c7Ur9auAhX7/M/lzIB5I/Bt3nrNgNIfGg5h2TQAItj8T4BRRTAV2hH4wGz7lMFyEPeGlUYwqKe/Y8FohfFy2qnWMZtjMaZdZYsQB4YnsPECOeGt1TdBrMSTthOiCdqUCP+n9FqT3PrMT5gJfceT1LQpRzmqVod4kA5D65oskTiPj4c/2wp3gSX8zRjW5Dn35pOhebxgqGL1uYsBVsc7zmykKDDXdwzEPtl26Eso7bmOzAVsSlYzHpCiHxGXw03dS3Ge09eEkvcF6+Htw+5isFACyWt6dYPxNsN85ajhV4zZykD8poi4fIvZuHERxTDnYsC1o6YPNCok/uvUYRCEmUq1JYGI8zCuhCxI+qKioFCUbuOVkQPmZooJWaux7yT/hDDHhQFHeIyojOC7neveiueYZ8YmAb64DAikZ+uoW/OZbDImuoizQ==
  template:
    metadata:
      name: forgejo-ssh
      namespace: forgejo
