image:
  rootless: true

signing:
  enabled: true
  ssh:
    existingSecret: forgejo-ssh
gitea:
  podAnnotations:
    k8up.io/backupcommand: forgejo dump -f -
    k8up.io/file-extension: .zip
  config:
    openid:
      ENABLE_OPENID_SIGNUP: false
      ENABLE_OPENID_SIGNIN: false
    queue:
      TYPE: redis
      CONN_STR: redis://redis-master.redis:6379/0
    cache:
      ADAPTER: redis
      HOST: redis://redis-master.redis:6379/1
    session:
      PROVIDER: redis
      PROVIDER_CONFIG: redis://redis-master.redis:6379/2
    oauth2_client:
      ENABLE_AUTO_REGISTRATION: true
      USERNAME: preferred_username
      OPENID_CONNECT_SCOPES: email profile openid groups
    server:
      DOMAIN: git.int.imdevinc.com
      ROOT_URL: https://git.int.imdevinc.com/
    service:
      ALLOW_ONLY_EXTERNAL_REGISTRATION: true
      DISABLE_REGISTRATION: false
      REQUIRE_SIGNIN_VIEW: true
  admin:
    existingSecret: forgejo-admin
  oauth:
    - name: "PocketID"
      provider: "openidConnect"
      autoDiscoverUrl: "https://login.int.imdevinc.com/.well-known/openid-configuration"
      existingSecret: forgejo-oauth
      groupClaimName: "groups"
      adminGroup: "global_admin"

service:
  http:
    annotations:
      metallb.io/allow-shared-ip: forgejo
    type: ClusterIP
    port: 3000
  ssh:
    annotations:
      metallb.io/allow-shared-ip: forgejo
    type: ClusterIP
    port: 22

persistence:
  enabled: true
  size: 100Gi

httpRoute:
  enabled: true
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - git.int.imdevinc.com
