apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: convex
resources:
  - namespace.yaml
  - backend-deployment.yaml
  - dashboard-deployment.yaml
  - pvc.yaml
  - sealed.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: ghcr.io/get-convex/convex-backend
    newTag: latest
  - name: ghcr.io/get-convex/convex-dashboard
    newTag: latest
