apiVersion: v1
kind: Service
metadata:
  name: convex-backend
  labels:
    app: convex-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3210
      targetPort: 3210
      protocol: TCP
    - name: site-proxy
      port: 3211
      targetPort: 3211
      protocol: TCP
  selector:
    app: convex-backend
---
apiVersion: v1
kind: Service
metadata:
  name: convex-dashboard
  labels:
    app: convex-dashboard
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6791
      targetPort: 6791
      protocol: TCP
  selector:
    app: convex-dashboard
