apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: silverbullet
spec:
  scaleTargetRef:
    name: silverbullet
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: silverbullet