---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: silverbullet-creds
  namespace: silverbullet
spec:
  encryptedData:
    SB_AUTH_TOKEN: AgAsg7SsPYOga8gmtJ83wz3vwiVAUu6na+UeP18grVc5bHvgBkfy75EsdaLUYrjKTeqHBXi2iR2eIrantMAsBaR7kD67ipdyfNhevFLZOELq8EsAhHdAB2mppN+xkdk57HHPtFzzOn7Y44ysw/evz+8oeFTrOSz74CNWJJOX/sHBHMN86ElGjZU5AL6opWW6+cP+mFfZQ8zzqvFaTBpgpP2smEGeFyo/26td+KvOLC+Ua9l+hfX+tOO2G2jlK39EDL+aE2PvVN+dykA/2U/ePeKQEj9FzowbCdr1GFEPMV9cPsldyRcajEcO8LxmwQiToZcifRsqtfHh/Mf6sjdEOBFwTCcHnb17QD3n+FQqfPXZmHdJq+ae0UiO8tYg5zNV5u+lXIgMO9WRfyvBjX4DYGcvIri/J3kSo6oTFh73EL1ubfRgGZ+X9XdNNwZbEM/NyWxCTuBViLa6dKrbVV3kJMj3ygq1dsv76aFoG6er+RXT7wlYMutbIer6JbRFErBKiB51EZ7HZvG01H5XE9DKfn5w/Htth46ScJb2Nx6NczFjL/DH44BSjtyz7ALudWIpMO2TcplLFJGaYUp05ETck4x/S/s2xiqQUG+mdGSiHU4pMrpuQwE02nhLE+rj2yUGP1juJQysW4CEyT5OM09SfHzwla6QJ5pMrtiZ7paTGkGOhsvH/FoubNpK0ETLDQL5tWcOxxuXGzXZTQaeD8Lk5lcQHQL0Pw==
  template:
    metadata:
      name: silverbullet-creds
      namespace: silverbullet
