apiVersion: v1
data:
  OAUTH2_PROXY_CLIENT_ID: ZGJmZTI3ZTYtM2JlZC00MzYwLWI2ZWEtMjljMmE2ZTVmNThh
  OAUTH2_PROXY_CLIENT_SECRET: SnUxUHNYeTdRa0Z2MExzYUt0a24zMWU2eEw1UGZmakw=
  OAUTH2_PROXY_COOKIE_SECRET: ZmxKSTMyMEM0SzVLeHVzSWg1ZGU1VUxaY3Q1RkNYRGVWSHVRZ3lCNVdOVT0=
kind: Secret
metadata:
  creationTimestamp: null
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
