apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-data
  labels:
    app.kubernetes.io/name: hermes-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
