---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-creds
  namespace: mealie
spec:
  encryptedData:
    OIDC_CLIENT_ID: AgCgIcTf1thPmKRpg2AnVq0HeYy7CZDqAqnRDzZk9cYlT9czp3cq8F4bqkgITU+en75A6R/GhVecJ6kLcP7c5Wgg34syMPLl+KtE/Ddnm79SqASt8bGggg9tg2a06bHd2D4HBQDiYeIWCNgF9sZXJ6KdCeWqWwhRanuLMXWKTYkLoosJYQHM1eUbaV2swiZYbYfFJNuo+6vEL1A2RFsxz6fKAC6Guh56Ky36Oc35LWWlYV/rc0xhosfDIiGj8h5YpC3SUq34Yw/KQkhDXV67gcEGBn48Z3jT84snxtKy70RB8oLNM/ERCwM5wUI0LZJ8ulsO+NY1IxRA+Ty9IyfVvsfIfDJPz6bgLTq5q3VG1CAfTkh7QSIhOUut1zHlYawYp/SLul6Xnc2Oy10Q1Z3vjPA1eIF3905oJMTQeIU/C6eVuzMGF1QS6R7MlHgL/z0ZpNH+vyZ2FUwfB7WgxV4f/GM7afZIWR3ivDAtRlqroPxpA0emnqb+w4eGcySmGju+nCQeHJ1PFYbxiU5Wgb4aqNH0JEEqjnBravbEfGu4OH4VFsF9HrTVxsrx7Mvdp1UCwT4jU92rN1p6vDiY3ZnrwDk4F/ivW1xxqTvcKa/eNhym35glzWxvH9W6jGOyU5w571ZTt7TqCvRAi2+MLc91E7GKYRTIRZIrls0c++cjAf2/h4nGA5+zZ77J4NBp7k4o5VQvoXz6fA/3as5wEaTR/uIBFdPGuFDJ36mVlPkjOYHC4QwqL3s=
    OIDC_CLIENT_SECRET: AgArR+/wQyKWL6eYQy84mN0+kiMBRfFOLzl0aP2ZxjYGC307xDRS7q/TW95d70zfHn8Ufivfk8sS42gUb0S32i99bayt6Vi1pTu/EBiip+0AkK7/g8d0g1cqTCy4kPpCIpKWifiQamTZ76h38uEkZ7MIZCGu/t805nwWByBA3dLjsr6gLPB2pTBIx6ZGf9Fdy6EiGE4+sPwbcMXZ1TVPEKhe2rybFrkugNtxiDPy29t+IhWsg9x8Kn1LPUGMV2MhhZ+oc6R1i3IXI7NLpAamU2z/IKLwAhULHvFfCXBQdF+kqmPQ1U+BD5r+pUCL1ERqXpji14qajDKbtGFX5EItPChpKr4JXwHLc4/6A2XVvodkoQd739MoxuYQzcYJoEzyr7GiKFQYTiz1siZA1NmmmJ8kfrYx8U+1Y+IDYnEst2jHfE5DcKpokZTBBqLQrlwuelcH86JO3zjeyxU445nwC1CC8kKf6g01vhLCLo1UHZPGcCfyRicrZ7+SEP/AOgPIHnmD7+oTN/kG8+l1zwVW+R2KlTU6ezrP1XmR0Z8wBEQaBOOP1JN8k4XBvnbp7JuC0vI09fzXB1Eql0IloMStfBE/NRtQj175FUD6Ndv7oIA7Vyppa3pcOfpArIK3EcHK+88Apz7CWowwdkBu7j8sEg1bKiMgqA9RvBhE/kfXP0EKkWEg2VF3aEVSiP5Mo6OZvtEVeCoQCdokJ+o2dGM3W1vUx2m1eYFZSdKwltqwMbfuRw==
  template:
    metadata:
      name: oidc-creds
      namespace: mealie
