apiVersion: v1
kind: Service
metadata:
  name: lorekeeper
  namespace: lorekeeper
  labels:
    app: lorekeeper
spec:
  type: ClusterIP
  selector:
    app: lorekeeper
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http