apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minions
resources:
  - deployments.yaml
  - sealed.yaml
  - httproute.yaml
  - rbac.yaml
  - configmap.yaml
  - namespace.yaml
  - pvc.yaml
images:
  - name: ghcr.io/imdevinc/minions/orchestrator
    newTag: v1.18.3
  - name: ghcr.io/imdevinc/minions/discord-bot
    newTag: bot-v1.9.2
  - name: ghcr.io/imdevinc/minions/control-panel
    newTag: panel-v1.10.1
