apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minion-auth
  namespace: minions
  labels:
    app.kubernetes.io/part-of: minions
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
