apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-add-ons-http-scaler
  labels:
    app: keda-add-ons-http-scaler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: scaler
      app.kubernetes.io/name: http-add-on
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-add-ons-http-interceptor
  labels:
    app: keda-add-ons-http-interceptor
spec:
  selector:
    matchLabels:
      app: keda-add-ons-http-interceptor
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics