apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure
  labels:
    app: sure
  annotations:
    k8up.io/backup: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
