---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerauth
  namespace: imagepullsecret-patcher
spec:
  encryptedData:
    .dockerconfigjson: AgBGNfx4+BGpF6hQSWGiMzV7tGWHL7ipGLD7RUh9EDXaL4GeMTm6hV5d6myx2iqozdl4KowZSkq37HJc2+OEx5KI0V+GX2Wu4dpdZyWa36hNJz/v+7BW4H2araCom7UDmctSF5PJE8ni/CXvZdEbjf6rLPRvUaPJqBC/KY2G7YUdENYFAHZxLpanzFENvrOE1ereAIMqVed/ReOeSpaVsd2IcwKhlzz5LwZUtmxauwYBL6plW9ecmH+kWvF6FEuqqUHjU1jBCdXqNmp/55jM5hPxJga3BG2CBu2Z4ToSHLssAhEHckebKyJ8hyIMuKhGQx60R+elhKFKFzEdaHHx9Gvyh6VQAa0oGlZ2B4zmjYoWoxTo6PlxVDMqvoCu7JQ5ZLL1H2jkYxJlMQOTjeKwN/lTl2YvgpmP6fLDOrgo1Uso4cNweo7zrCKswUoYs0hU0BxMSPAPwfwHtWRs7xhK7zXP+hzmag/o3u2iDQHzpn65+Q6E3z2FNMhiYinI1EY/jUCXT7K4tGz5s29/K1O45jpGN597+G+vZqMSOjPc3zxylS3uQVNz/dOfTijrbno902Be3SZQjHrlVzXqQCSiU+oISMO9lrN50ZVu4dGRI//MsxSUH0lES/cRsdRUTNhyQRxTF7ZLk0ko+buIDwbBhvHehi9GOkW2iN7EzTPuoxiRXHzmpXe/5H3DEb7zZsRAL7Z4n/kfA3RZitcI4qwkk1lm3cCm2pg2fFDZ7NRq5RyetZ7MWjBzRXoX/+pi/zgAYv0fYf2jNjgMzKGlMdkEHr4KwfdvF6e6fOuHqIJcGGKxtWK7ijMHLuJD7MW9xCBBQeMUCJpI2VNqHW3QqkIeIUmtxCQ6mTm822aZurpLmkwCYil6HlnG3xVzjXMDRSY7IY/hL1+wh4IW6dG71UbqT2o7vo0Uw4Yc1upv6/aaBKZIvwqQMUysotSx36Yyz0uLX9iAXIImmA++ZV/NUYG7JmNH2m43HvVeEQAIGgF/q4NHkhoF3hGJniuMbA==
  template:
    metadata:
      name: dockerauth
      namespace: imagepullsecret-patcher
    type: kubernetes.io/dockerconfigjson
