{
 "title": "GeoIP",
 "tags": [ "nginx" ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Access by Country",
   "type": "geomap",
   "description": "Count of how many times in the given range distinct IP addresses accessed the servers.",
   "gridPos": { "h": 27, "w": 20, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (geoip_country_name) (count_over_time({job=\"nginx/ingress-nginx\", geoip_country_name=~\".+\"}[$__range]))"
    }
   ]
  },
  {
   "title": "IP Locations Heatmap",
   "type": "geomap",
   "description": "Source IP addresses accessing the infrastructure",
   "gridPos": { "h": 26, "w": 20, "x": 2, "y": 27 },
   "targets": [
    {
     "expr": "{job=\"nginx/ingress-nginx\", geoip_country_name=~\".+\"}"
    }
   ]
  },
  {
   "title": "IP Locations (non SSH Traffic)",
   "type": "geomap",
   "description": "Source IP addresses accessing webservices other than SSH",
   "gridPos": { "h": 26, "w": 20, "x": 2, "y": 53 },
   "targets": [
    {
     "expr": "{job=\"nginx/ingress-nginx\", geoip_country_name=~\".+\", dst_port!=\"22\"}"
    }
   ]
  },
  {
   "title": "IP Locations (SSH)",
   "type": "geomap",
   "description": "Source IP addresses by location accessing ssh",
   "gridPos": { "h": 26, "w": 20, "x": 2, "y": 79 },
   "targets": [
    {
     "expr": "{job=\"nginx/ingress-nginx\", geoip_country_name=~\".+\", dst_port=\"22\"}"
    }
   ]
  }
 ]
}