apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: city-council-review
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: city-council-review
  project: default
  source:
    path: charts/city-council-review
    repoURL: https://github.com/imdevinc/homelab.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
