apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  project: default
  sources:
    - chart: keda
      repoURL: https://kedacore.github.io/charts
      targetRevision: 2.20.2
    - chart: keda-add-ons-http
      repoURL: https://kedacore.github.io/charts
      targetRevision: 0.15.0
      helm:
        values: |
          scaler.replicas: 1

  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
