apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: macro-track
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: macro-track
  project: default
  source:
    path: charts/macro-track
    repoURL: ssh://git@git.int.imdevinc.com:2222/devin/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
