apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: matrix
  project: default
  source:
    path: charts/matrix
    repoURL: ssh://git@git.int.imdevinc.com:2222/imdevinc/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
