apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcphub
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mcphub
  project: default
  source:
    path: charts/mcphub
    repoURL: git@git.int.imdevinc.com:ImDevinC/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
