apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  project: default
  source:
    path: charts/open-webui
    repoURL: ssh://git@git.int.imdevinc.com:2222/imdevinc/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      
