metrics:
  grafanaDashboard:
    enabled: true
  prometheusRule:
    enabled: true
  serviceMonitor:
    enabled: true
k8up:
  skipWithoutAnnotation: true
  envVars:
    - name: BACKUP_PROMURL
      #value: http://prometheus-operated.monitoring:9090
      value: ''
    - name: BACKUP_GLOBALREPOPASSWORD
      valueFrom:
        secretKeyRef:
          name: password
          key: repo-pass
    - name: BACKUP_GLOBALSECRETACCESSKEY
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: accessKeySecret
    - name: BACKUP_GLOBALACCESSKEYID
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: accessKeyId
    - name: BACKUP_GLOBALS3BUCKET
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: bucketName
    - name: BACKUP_GLOBALS3ENDPOINT
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: bucketEndpoint
