{
 "title": "Internet Speed Monitor",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(internet_speed_monitor_download_speed,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "internet_speed_monitor_download_speed{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "internet_speed_monitor_upload_speed{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "internet_speed_monitor_latency{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "internet_speed_monitor_jitter{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download & Upload Speeds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "internet_speed_monitor_download_speed{host=\"$host\"}",
     "legendFormat": "Download Speed"
    },
    {
     "expr": "internet_speed_monitor_upload_speed{host=\"$host\"}",
     "legendFormat": "Upload Speed"
    }
   ]
  },
  {
   "title": "Latency & Jitter",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "internet_speed_monitor_latency{host=\"$host\"}",
     "legendFormat": "Latency"
    },
    {
     "expr": "internet_speed_monitor_jitter{host=\"$host\"}",
     "legendFormat": "Jitter"
    }
   ]
  }
 ]
}