apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - alertmanager-creds.yaml
  - alertmanager.yaml
  - alerts.yaml
  - operator.yaml
  - prometheus.yaml
  - scrape-config.yaml
  - servicemonitors.yaml