apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifa-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fifa-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fifa-bot
    spec:
      containers:
        - env:
            - name: SENTRY_DSN
              value: https://28366be412ca9a9c14cafc902f55d890@o4504167699382272.ingest.us.sentry.io/4511771177254912
            - name: CONFIG_FILE
              value: /app/config.yaml
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  key: SLACK_WEBHOOK_URL
                  name: fifa-bot-creds
            - name: LOG_LEVEL
              value: DEBUG
          image: ghcr.io/imdevinc/fifa-bot:2.1.3
          imagePullPolicy: IfNotPresent
          name: fifa-bot
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: config
