apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - deployment.yaml
  - sealed.yaml
  - service.yaml
  - httproute.yaml
replicas:
  - name: fifa-bot
    count: 1
namespace: fifa-bot
images:
  - name: ghcr.io/imdevinc/fifa-bot
    newTag: 3.2.0
