---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fifa-bot-creds
  namespace: fifa-bot
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgBLgP/HRLCr6nwwuPLBCWbvCIqMD1wRkTCFvKVl3eYKLo8V6k0qUI5yqx8XKm7cVpPbWLVTHvbB8Oi+0lOVRghQPUmnYLap4gTfxpuQVDPznJhWiBHJPBbwtfuD3IH5fAzBcB2SoaM3PnP1FIKcpru7Bq5xDHuuVWFuoZ1KbRSapq2Hwqn0NS7vvurIop9CArrz+BKOqwzYkcCPMIQmYD/MY6doX8BbcrdxvM016Ubj2pJjtAxHiux+BEyJJ5CkJ1rgdCqPjFc/PEAif5gfbwYk+hIYsOfAHXyIp7H9nilI2Q0RYvhDyzdCKs3Pbn9S4B9SozSVMk+bbYWKckUWTLpqiLbsmTrRWexnpFhwT0J0dsGlONNlnWdcNY7IEgWcbtxizPVB6vhxYhAY/ezOaNS/7eGdLfxiFouSX7w1IgSeIXUWcCEcbeKIW0utdwR+jKQerbeBv7PCvMrM6DiPLcO5/QzOa/pvlpgEcxq6OP0Y/qc6SnomZVw2/703PONFqABnP0E2gtvrCn+DoVa0rFbMptumqYqM1f0rcRFrjFhMii/4ho1aouh3efmxxrpv2QjnSU1ahAPnH0TmliaAMavJ46za1TdCt4ydQlKDznbpM3F2Nn3vX7JSKB3PZcy+TKQlZzviARYK7Vu/FQk8PwcRW3KC/rZvMcmuzscXXqN0480hSpaDHcp+Yxzsrk2mYrJfPH8fR7cC1u/Y0Z3q203nClh7f9U1u7ekgwcNBEAuCVhj4s2qilhsAn6nBgLDkf/IOxeIlHerhhioqrly0C8otz/LJIkTjlC6kei43Y9S
  template:
    metadata:
      name: fifa-bot-creds
      namespace: fifa-bot
