---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fifa-bot-creds
  namespace: fifa-bot
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgBpLnE2swn7jetNZCB/LW9TJ7lGln/hiJRtDfbbRIL32VY+LTr7BFOJXytNEZx/yXqROIDltVcAin6EiEfFALaY/4AamtAGa7I2Lilwd3EHiEsMOZp+FfiAi9gHZoc9eTsJlfGXyprlBsOPbcK9dzmH+G0Mbf6z0kAVJz/byaetjCBm6jisWGNRAvyy2o//H7A1oEc5SAi+KX/Z1eXSJ7dEYlJ7lGKGBgjFMhvMiMSKMBmWo2LWyubasJ6I1C0tdQrrxr6iV2UMtCxSfnzshTFeH+bKf27MbSvTDFI4Ku/NGLRMG6z6bHzsDMbA10xvUnM+gkG57m4HBkY+29j3qOyTeD4juVAKb5ACoVpkaY/NQTClgL5kGgx+GaQO6AsuG9JjORGc79/Rqjhvyngu1/GWNGsDrh3/3EzIwlAT7ba9SvQbCgd6muVF+toG2NAGwaNSMVYUY3ETYii2VK18PtLiGMM15fyKsrDU6qWjTeiMDYwd5tN+9PJrr/QmgTLu9JV78PiviaDvYQlvnOoIMzuvE3VXMx42ZuussC4+zHDNBO1kFI/Ua89znLS9hMY77Gz+SHPxHl3BhjLelcClU+zHpEyDbMV/8jpdQUiRLU5h9M8k6GmpiFHRicz+a9q5oH0q3KRwpr6yMAQn6Ip43X1U+uH985WaRIEp6nzu3JTsGj3aaZRPAkWyc/Ysm3UPOJeSqW34xbXOo5m6lbiKkw0UqqGKBQ72vg0Co14RxfIGp3zGOhzEUj86jWa/gh9gW0Dm3DJ9ZWB8y/kvVhcD67yrdvV6YrpxCm0oPpscpIdq
  template:
    metadata:
      name: fifa-bot-creds
      namespace: fifa-bot
