---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fifa-bot-creds
  namespace: fifa-bot
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgBbvsEL2IQV4rfu6ZQemCEjX7t1Qy2rhuaLfAWFP5Cbi+vAWmmWbO+jJ5HzXXMQJEvcx44C5r3eupvcPiRZNHZxOzTiDoLsKyw17O7SUIjLYKVonE1DN2v21pw/0iz4UxVqtb3fSBZtKe3QLWRLq8EdNkBdJ9SPNO1n7Ec5ZZHyGVoRMmHcSbFZh9+lZCSGskvWnJJTUJoq1P2tEhGJhhpG/0PdvC/j37OLAGK8cDQiQIouYGT/hbj1NpUx3YMRVf2ep2SHg4Yn6CRWNKnMs5Z5C7h2e6XD8jj9YVGg3XT3c4eEMX3xIrWZhsR5hP2dGjqxLb/q/c9K40nihEVjZQltmpBriSlk4X/tRBZ8XzC3B9W81mjraZtobVq9AsxjeGWOgIRAXw53PY2FCZrhOGn51BNkhCqmwRkFbZCg/vGewCqtH361k6vN2IS+Bv++GqJN1wTqrGmikxN3Ajkbyn5w7OdRfOUURAFiTDJ82ZI3U+Ml6yKx/piUEHtNEwExIpLD/PBuXfGdK6yZsEwJCCwC4FppXbcT5wVwwUlLfWAB0hJvIDT0MNbcEP2BoNrPfHprEcmlhH1AiPCShIHavGWRUd17tp9d91Nqs8NxfU0fXf2SwRqBttDEsx+5LV4UqwKoI42arkWLljE5IUPXnsJ6wlDSjZIMXvPJb3Ghj7ApASNl7E6Cvf/TLVgUyHwSYmTuU4aLkUixEXDmFXcDvQRXoHna1T4Sz2MDeJsRIKFfinQCRwAL3RMf6uQdix/yZjtFqctUYfb0WelkabYXwaAVGgHxvzpQX+vkqlkJOYYlLfY=
  template:
    metadata:
      name: fifa-bot-creds
      namespace: fifa-bot
