apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dnd-cards
resources:
  - namespace.yaml
  - sealed.yaml
  - service.yaml
images:
  - name: ghcr.io/imdevinc/dnd-cards
    newTag: 0.1.0
