apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mongodb
resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - sealed.yaml
images:
  - name: mongo
    newTag: 8.3.8

