apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
resources:
  - statefulset.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - exporter.yaml
images:
  - name: homeylab/tdarr-exporter
    newName: ghcr.io/imdevinc/tdarr-exporter
    newTag: 4.0.1
