apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-config
data:
  REGISTER_ENABLE: "false"
  ATTACHMENTS_FOLDER: "/storage/attachments"
  BACKUPS_FOLDER: "/storage/backups"
  ASSETS_FOLDER: "/storage/assets"
  SQLITE_FILE: "/storage/trip.sqlite"
  OIDC_DISCOVERY_URL: "https://login.int.imdevinc.com/.well-known/openid-configuration"
  OIDC_REDIRECT_URI: "https://trip.int.imdevinc.com/auth"
