apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trip
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - sealed.yaml
images:
  - name: ghcr.io/itskovacs/trip
    newTag: 1.44.0
