---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-creds
  namespace: trip
spec:
  encryptedData:
    OIDC_CLIENT_ID: AgCGmbj1/dUPOGlxqDbBSLGnftFvHDaZgqSEwWvR5+6h3YHkjEYrnKaNUirtscd8iIVlLOkM4mW/VlaYELmCHQkM/ycli+sFIaCOzKKXg21PnFOr3Z7co4jQlNu/vBfBoGhANvetvNV3oxWkb38xfT+cdPlsXi4zyuHgPK1dK7+sM8m/qmFUrZUp7uyPxTF/krid0BowKUMz/64S6d66yjUv5dj0coAXPQsIRWoAmmXH6XmvGvrf/6ampYFMqYj2kkelP1Hpz3SLVJlf/PUk/2IIBZrnDKHk9nHtnYznG056dwv5pV2RSnj8GwE8yxvh9odyduo3mhOypIFEqeNcsm+WWMitB53nFBOkZ8/rGZk2AVc18jvSkIRtbG2gNqJVLylz71wE9VRUkt86tSIioLKjCYKdSLKaURac7NJg5M/uFNcTum5mWT6Xh6MyV0iIn7d5X5eKkV5WpTShI24nLxJsexLQMcZT/RimRM/of0EHqwuydHP2v8rg3H9xZff+Sf4vBUR94j9whkyj79Y9V6V1n6BYH0Ci8C0cNTu5iXGW/SO56lO0X1UwEtNxChGUD9Qp2XYm8SUbOFHM+EmShupIBRK7E7KVaJPSeDbVnBdQ3OX8ryuU0zN2EHD/mxeZEU0v8E7ymy/fvOg3rm9inN31iGn2Nj+Y5jX9LSHCBP2FPLpCE2cIT4a7URrTxyfO8UrH5o9XK7Edf+DciRuVtk+7DG2gQQbA4NrjBrD4mPt1SMNIYKo=
    OIDC_CLIENT_SECRET: AgCRKXH/KzrERIzv70nLVnujphjGm1anLMmeitiusCsZZfXVRtOtt2oN0lwBI7bHoXO4iZBJGeNr8C7QJS7g0N8CJHEYG9HKWDXtKw+V5C7Orj2Yg0t2pViZtsF3+97uXGqCeNgX7+MIHjdt3rvH5BpAeRee1qZKR9FjJUlBerk3lPhiItMLWI56CTHqito+KSbspAq1eCCbZ8e4HDH8LhYgnTIgd10eMm3gsm9oIXEAzChq1NS6A26+Pk0RitHLLMQX2qZx8eAc8HApGgicz/Q0T8XLSpBWF5RAA7L0p0JtzXoV+wL9xIA0W6enARA+Gi4advRbHeoqwdtrLCLRCUqS0P2s9EPxfSpcGGVYw6koQnirjp+ZDPP6rteTuzTtCC7UpevkeUcF4eOaYR77SGpgW5gX1W5uuuFq7XHQZ582J76tkY9jhfrLldsXbNTrlLZOUAgpog6xt7Nw+YzZAg5FT/BPFWCGtATqZ2WEU9QVmIPnKQLugSvl5vBUBHEaSqRPyEOnI6KJwbo4xw+2vZ9MXPhVZSnROMKL+ZJg5IrUCAancbzrN06tFEB013yvFkcBHmHi6XBgOwsxNptMDzc7r9n58C98Nl83AF9KTriIe5n+vkXV6edKl/etHO5cjw73mCU+ZqPEeMz1ASY4fWhy3UNFFo5Rh/F7i26KGiPBR0wlquN6lcnrbIj63Aj/OPfa+BPh9j1CYPvy2ay9nsGwC+JViW/p2lJdJiswtZBi2g==
  template:
    metadata:
      name: oidc-creds
      namespace: trip
