---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets
  namespace: mcphub
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBAqQpX2nTU4MPY33M1VTpjrPPLDjXq3tKWXBbLuWXbWgkIAMJlnFWkw+oCQ9UOAV35bcBEN8C1q/wR9KMmVORT4Yau5oUb7X9nm8e47IHndoqiXxxPTtnxDO9TRvHMOwBU7nCEJr6HpsnGOZumYp/dkqDrL+OlccVwLEPdT45X6YDQkXRyR70J3exZwz+jZMUGlRU+hieXi1wfRl4025VTsVEsLIzTWjGSsDYZkfNugzZgvQ5xjx0FELAZ5Z/kX02oadYLYmJtE6hd9ini5uR2y9/yJfud6y6IsQ1ebefzZDRAIgt09BjGVqGHFtXy/0YDERY/gBy+nffjurEHWBr8ZleY3nwHd+ST57OhZL7UNG8JnB+8H5AlQMWyS98lPaROvv8wIvtSz9o6anK3V3eRpxqmgRBZwnixoWtjd7KgJ90YNxVJb2n6PRaYjNgXW/PkpNuaDLpfsBgc5+jqZrHLiZJfenkcXQ2D3ZfqL/cjKA72VL3UmWxxsGBukmB+gVqIavLC/WsgqC3K2vPabbErcbLbeiDP6Npg5T3Is1MGAZ23h6awZ/3e3cKvd4rK3nYjsuFS9qC2sYmiIbGyjUe3Sv6AAxijS9ZjRD7QnFrZHiVhudAICC/Cm0i7o1HvujWgyKa1WAlrpzi2JEVvI6G/0gXonMBHEQ+nMmoUAXql/vu9g4K/hVNocdzRSQIVVUhkIc9Cjx2u7QJ48buk3Lp0wgeS6A3g8w==
    JWT_SECRET: AgCYwmzJUuGB4t7T97N40ZviVwp9to1d8TphpHp/Y/P5FooKIFttpG2Tw0eb/HUaoSOewxZW5K2TK+iWkPTBasiIsrEKf91XUFZjXRtCMHGkrhnwNG5kJsDyRZjoXs1+3ZZkjYTj9+nB4ZdU+WKKFH9YY2K8uETYNz8OTQ+h7xkQ5hNtLON5yHo5jDBfXc/+ZQ+fKb/3j3luZfEqFGZfwFV7heZKdFLDQhMd3q/+XzRL5STlun+y/hT30Fj50Y23Wc56PhMDeLotnsHpQdlV4SagiAhhx1APe4Si9UrWFkoscGxxtJYLsMzlqNLf2ZyT4sZTOkC7BN/lG49O8cnbB5CB8OOAHTAQG58Wbn0uoFmXDj+90TDVg4uEChC8KXedE5nJ3ESCAkbh4MV8GvHDW+8ZSS3gwZ1d2I0oPnklb4ohEvfJ7K+wcqvBX0JFL+U+iKeU/aLYLC5dxO5YrxUNSO+3ODIVl1P8JZawfxS0D8kpi42NqMQXiX/oJ55sjGj8yUpIDPfHR/EXow/5VUCPUaGMcTWkWUVCA2asUGuAwBH4B0fPYA6EJzJfAUGAhIoKmRmHhfDpNIBca+WLlFKWPACx9CsRL5E94a7rnbc7jW/Lxjax5fe6rEE58A4vHBLCq7nZhYWTnow/ZoTf6JOQIqDq8/A0IZvclRgvAwZSjK12DQvSZdb32kB0RzmuwXqzhTJDmMu8gIvDG8YFl11wazL4Y0Wz779dhQwSYiHdVsGAtk07grvDAiChhRXB4SqKbV6jv267UBJaErvNs8d3veED
  template:
    metadata:
      name: secrets
      namespace: mcphub
