{
 "title": "Cloudflare Tunnels",
 "description": "Display Statistics for your Cloudflare Tunnels (cloudflared)",
 "tags": [
  "cloudflared",
  "Cloudflare Tunnels"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "IP Locations Heatmap",
   "type": "geomap",
   "description": "Source IP addresses accessing the infrastructure",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"cloudflared\", geoip_country_name=~\".+\"}"
    }
   ]
  },
  {
   "title": "Top Hosts Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count by(host) (rate({app=\"cloudflared\"} |= `host=` | pattern `<_> DBG <_> <_> <_> connIndex=<_> content-length=<_> event=<_> headers=<_> host=<host> ingressRule=<_> originService=<origin_service> path=<path>` [$__auto]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Hits by source IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(source_ip) (rate({app=\"cloudflared\"} |= `host=` | regexp `\"X-Forwarded-For\":\\[\"(?P<source_ip>\\S*?)\"]` [$__auto]))",
     "legendFormat": "{{source_ip}}"
    }
   ]
  },
  {
   "title": "Cloudflare Edge Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_ha_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "description": "Concurrent requests proxied through each tunnel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_concurrent_requests_per_tunnel",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response By Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(cloudflared_tunnel_response_by_code_total[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(cloudflared_tunnel_requests_total[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Config Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(cloudflared_orchestration_config_version[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "increase(cloudflared_tunnel_request_errors_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}