---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgBtt1J34Q2pnks6SKAehVRpGqz2W8Oq7q0zMYX7EDJyUfiB/vjzXWUGj+9SzjR3lam7KiK/mvxhO4COS6UeQvQzBtOmzqSgEpOzL/3C8EFASUa75MhRj9Hj11LXw9w1mkoY8Yn4iJWo7yO7kmxDv92ZvWoRBH9sSXR9lHKkAYWqv08whuzo2r9QAAUdJk8v6nju18FT3PpLUd7/Tj/+9G9/lET6rMWvVb/i9ecvdHMoZ17cyoSWl8G9aH8fhRHd50/26IYn6h1grungxS9zablSNu/bTxG9i0AhDEQ+rDR4tAH0AtrJzMLDXjLXK0ojupD7EkunQT4Igq+Y0tvIOvpbx7ayuIc7te+btrK5zRKWVZicbTYXVHiXiFKzttICqo5BohHcPz5IZrL5KcLfmwLIK3CUwBsQsFqyL/UpmyGvgXrYh5HoJY4y89cnTizJS6gDsVc3deXrkQ4F0HLDvEP/nzAHE2FXxu/48jWPx+zoEpyc3+G6RTLqHK0LJOo6HXicnDKD1Lsc+Pny9A1UmnGcSdrKd0c/tpCe7zpfryneRHGlePoOzYW7GXexLZmFaJVUXtPmwbUGF/qChfktbsrYI2d4yXbNwvU/FSP7D9ITa/zqjFPQLjVbs6JS7TvY6SuQwfnxaY8H6dVRYQAx9huQuhCrYlByIv6kQaEPq7CUU1EVaOvlhlIM9ZQrcpWu/La9CkjkwvTtMYywD4tDZcJF6cejgVyH
    ENCRYPTION_KEY: AgA1VLuidq2qDt+LAG0yYCPr26R9PsMYAAmmFAMDQ+aMmz6ThaadCILjrbxfV0Js7POodfQ3ZdRg8vExjL+s3txeeIAURPXlkSOd1d5SRE7yelC/+FZpAzd7mKOjvlihZF7BFeETsWyZ6nBB+dIC8Ztaxc7NPqFcE++jm59YwNTU2U1BhUYmJHlKG50fWPEu5x2gmWY6v3F9idxvRbu1nXQSaOGjyWwwbniaH/rIt2qVKbanQgd90gJGX5buj93PGbZqg6FX4XF9y44hLaZf40k7Ia+QWW7Pvl/fY5FK1IlzJKmObkc7/yXN2zKqMDR21/UK3e+T+FHh1R0B+K4n3yCKHum6LuPouSvrBM6C8RcsJXnQoiGO0mtMz/5tdM70XZTXuowzDLuqpHWdlOuRS/xXSoURnd76uc1/fdYBIap/K0o23fW7Z6WFd+3SZJ/ZnVkPHHutZqkI3mOlD1/FdZz6LiRBdDBbQUmZz+mQNVKSIjNsjNeOjqMh7ROj33l6s+TaUdpiCDcRZfCZaStNeLE/lBCepjpA6ypxdtl1nrHmmM6LNDWWgmkbL26L7t3EvOSTGlIbfbHRj0AbT6knlX+wcyeSKt5km/SL8khNhzBEKCNE3U6hAcBjs1Cy8YFy6qNwb6i4nNivuLrWhK/+8hETnkk6GBk5TZANsGULTP9DLI2eldtXYWkBJSWHgN/1GEhANMXo360MFNp6g2wdReWciNW1Z93XRrpW8LVExj+De9gEkmxIq6mtlzfHUw==
  template:
    metadata:
      name: pocket-id
      namespace: pocket-id
