{
 "title": "Radarr",
 "description": "Radarr Dashboard",
 "tags": [
  "mediaserver",
  "radarr"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "description": "Status of Radarr",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Downloaded Movies",
   "type": "stat",
   "description": "Number of total movies available on Radarr",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_downloaded_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Missing Movies",
   "type": "stat",
   "description": "Number of movies released, but not yet downloaded",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_wanted_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Size",
   "type": "stat",
   "description": "Total filesize of all movies",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_filesize_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "description": "Free space remaining in the download directory",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_rootfolder_freespace_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "D/L Past Week",
   "type": "stat",
   "description": "Number of movies downloaded in the past week",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(radarr_movie_downloaded_total[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "D/L Past Month",
   "type": "stat",
   "description": "Number of movies downloaded in the past month",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(radarr_movie_downloaded_total[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Movie Quality",
   "type": "bargauge",
   "description": "Number of movies of each quality",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(radarr_movie_quality_total) by (quality))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}