{
 "title": "Sonarr",
 "description": "Sonarr Dashboard",
 "tags": [
  "mediaserver",
  "sonarr"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "description": "Status of Radarr",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_system_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Downloaded Episodes",
   "type": "stat",
   "description": "Number of total episodes available on Sonarr",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_episode_downloaded_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Episodes",
   "type": "stat",
   "description": "Number of episodes released, but not yet downloaded",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_missing_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue",
   "type": "stat",
   "description": "Number of episodes in the queue",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_queue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Issues",
   "type": "stat",
   "description": "Number of episodes that have an issue",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_total{download_status=\"warning\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watched Series",
   "type": "stat",
   "description": "Number of series' being watched",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_series_monitored_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "D/L Past Week",
   "type": "stat",
   "description": "Number of episodes downloaded in the past week",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sonarr_episode_downloaded_total[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "D/L Past Month",
   "type": "stat",
   "description": "Number of episodes downloaded in the past month",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sonarr_episode_downloaded_total[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "description": "Free space remaining in the download directory",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path) (sonarr_rootfolder_freespace_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size",
   "type": "stat",
   "description": "Total filesize of all series",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}