apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: matrix

resources:
  - namespace.yaml
  - sealed.yaml
  - synapse-config.yaml
  - synapse.yaml
  - element.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: matrix
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

images:
  - name: matrixdotorg/synapse
    newTag: v1.150.0
  - name: vectorim/element-web
    newTag: v1.12.13
