{
 "title": "Crowdsec Metrics",
 "description": "Shows the 'cscli metrics' and additional stats to Crowdsec in Grafana",
 "tags": [ "crowdsec" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "appsec_engine",
    "query": {
     "query": "label_values(cs_appsec_reqs_total,appsec_engine)"
    }
   },
   { "name": "machine", "label": "machine", "query": { "query": "label_values(cs_info,machine)" } }
  ]
 },
 "panels": [
  { "title": "Overwiew", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "cs_info{machine=\"$machine\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Since",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{machine=\"$machine\"})*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raw Lines Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total{machine=\"$machine\"}[$__range]) or vector(0)) + \nsum(increase(cs_cloudwatch_stream_hits_total{machine=\"$machine\"}[$__range]) or vector(0)) + \nsum(increase(cs_journalctlsource_hits_total{machine=\"$machine\"}[$__range]) or vector(0)) + \nsum(increase(cs_syslogsource_hits_total{machine=\"$machine\"}[$__range]) or vector(0)) +\nsum(increase(cs_dockersource_hits_total{machine=\"$machine\"}[$__range]) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parsed Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ok_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Whitelisted Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_node_wl_hits_ok_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lines Poured to Bucket",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_poured_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket Overflows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Buckets Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_created_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Scenarios",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, ceil(sum by (name) (increase(cs_bucket_overflowed_total{machine=\"$machine\"}[$__range]))))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Acquisition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Metrics",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type, source) (increase(cs_parser_hits_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "sum by (source) (increase(cs_parser_hits_ok_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "sum by (source) (increase(cs_parser_hits_ko_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "sum by (source) (increase(cs_bucket_poured_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ source }}"
    },
    {
     "expr": "sum by (source) (increase(cs_node_wl_hits_ok_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  { "title": "AppSec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "AppSec Metrics",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (appsec_engine) (increase(cs_appsec_reqs_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ appsec_engine }}"
    },
    {
     "expr": "sum by (appsec_engine) (increase(cs_appsec_block_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ appsec_engine }}"
    }
   ]
  },
  {
   "title": "AppSec '$appsec_engine' Rules Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "repeat": "appsec_engine",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (rule_name) (increase(cs_appsec_rule_hits{appsec_engine=\"$appsec_engine\", machine=\"$machine\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Local API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (reason) (cs_alerts{machine=\"$machine\"})",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Decisions",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (reason, origin, action) (cs_active_decisions{machine=\"$machine\"})",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (route, method) (increase(cs_lapi_route_requests_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Bouncers Metrics",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bouncer, route, method) (increase(cs_lapi_bouncer_requests_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Bouncers Decisions",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bouncer) (increase(cs_lapi_decisions_ok_total [$__range]))",
     "legendFormat": "{{ bouncer }}"
    },
    {
     "expr": "sum by (bouncer) (increase(cs_lapi_decisions_ko_total [$__range]))",
     "legendFormat": "{{ bouncer }}"
    }
   ]
  },
  {
   "title": "Machine Metrics",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (machine, route, method) (increase(cs_lapi_machine_requests_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ machine }}"
    }
   ]
  },
  { "title": "Parsers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Metrics",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (increase(cs_node_hits_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (name) (increase(cs_node_hits_ok_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (name) (increase(cs_node_hits_ko_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scenarios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Metrics",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (cs_buckets{machine=\"$machine\"})",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (increase(cs_bucket_overflowed_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (increase(cs_bucket_underflowed_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (increase(cs_bucket_created_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (increase(cs_bucket_poured_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Whitelists", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name, reason) (increase(cs_node_wl_hits_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name, reason) (increase(cs_node_wl_hits_ok_total{machine=\"$machine\"} [$__range]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{machine=\"$machine\"}[$__interval])*100",
     "legendFormat": "{{ machine }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{machine=\"$machine\"}",
     "legendFormat": "{{ machine }}"
    }
   ]
  },
  {
   "title": "Lines Processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 157 },
   "targets": [
    {
     "expr": "sum(rate(cs_parser_hits_ok_total{machine=\"$machine\"} [$__interval]))",
     "legendFormat": "Parsed"
    },
    {
     "expr": "sum(rate(cs_parser_hits_ko_total{machine=\"$machine\"} [$__interval]))",
     "legendFormat": "Unparsed"
    },
    {
     "expr": "sum(rate(cs_node_wl_hits_ok_total{machine=\"$machine\"} [$__interval]))",
     "legendFormat": "Whitelisted"
    },
    {
     "expr": "sum(rate(cs_bucket_poured_total{machine=\"$machine\"} [$__interval]))",
     "legendFormat": "Poured"
    }
   ]
  }
 ]
}