apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: manyfold
resources:
  - namespace.yaml
  - httproute.yaml
  - sealed.yaml
  - service.yaml
  - pvc.yaml
  - deployment.yaml
images:
  - name: manyfold3d/manyfold
    newTag: 0.145.1
