apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    service: manyfold
  namespace: manyfold
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
