global:
  domain: argocd.int.imdevinc.com
dex:
  enabled: false
configs:
  rbac:
    create: true
    policy.csv: |
      g, ArgoCD Admins, role:admin
      g, ArgoCD Viewers, role:readonly
  cm:
    kustomize.buildOptions: --enable-helm
    url: https://argocd.int.imdevinc.com
    create: true
    oidc.config: |
      name: Pocket ID
      issuer: https://login.int.imdevinc.com
      clientID: 0560d20b-7844-4efd-86cd-3e4109e82844
      clientSecret: $pocket-id-creds:clientSecret
      requestedCopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
  ssh:
    create: true
    extraHosts: |
      git.int.imdevinc.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/dZTMxdSYlDCDdV/FlhwPwi4tk+Hf30QYmHCzxmLBe0LsVMOsYHkvPTzLqjHg1lUi5twfkVy8Y5oueS+iOvd/G/QKxU5U6DOd19A7dKxC+Zc5yjfr6vpAhk6/ymVNKLhCmBlZjTcy/4q2VINez4gY8nBnHQB5XHzje1IYA0pYWaCvWII9iPJ6c4gR9aMWKlNv1tzApbftHF0jyo1gqHjTcMYdvAucX3LZo2wtpRvDOnFNnKH4w0avXgP8UcD+F/G1Y1ZRl+E0eOxEdrmrOB86B4o6YRJIQ9jYMNHzjNcDcT3oND1NKHoa5rOvwLxBa+t71C9mOqhUaIMlIWFwIj0xZaNsGiKfcRp5ypXvzDKMikvcr0GynWpmkCCeQcmI8LBe8s0FpjeF6tjgEvs0wFAYcgzv7c/8q0lcwWWroHhdcnSRPvWxGcr8kcu7FSWkIlJazAWgOoMDDQnyOknb1puRxNmZq7XAXlZPLH4t9IdIJE0hVU/ibvS+rsiREbuIyPju4DrHR9NedQE01hWWWog1gYoYxtuyLuG+5Y/h6UIenfclXarxKT6KGh2zwto9qJCHKfGkOjvf9muBkgS2oaYv5pYQLZnhQOUyAgU89lbnunb1slC+walMy0nsxR+OdfhtAdkEJZejp1u1J6AmVp23UbHZP9CODlX5eaeSJpI/cw==
      [git.int.imdevinc.com]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/dZTMxdSYlDCDdV/FlhwPwi4tk+Hf30QYmHCzxmLBe0LsVMOsYHkvPTzLqjHg1lUi5twfkVy8Y5oueS+iOvd/G/QKxU5U6DOd19A7dKxC+Zc5yjfr6vpAhk6/ymVNKLhCmBlZjTcy/4q2VINez4gY8nBnHQB5XHzje1IYA0pYWaCvWII9iPJ6c4gR9aMWKlNv1tzApbftHF0jyo1gqHjTcMYdvAucX3LZo2wtpRvDOnFNnKH4w0avXgP8UcD+F/G1Y1ZRl+E0eOxEdrmrOB86B4o6YRJIQ9jYMNHzjNcDcT3oND1NKHoa5rOvwLxBa+t71C9mOqhUaIMlIWFwIj0xZaNsGiKfcRp5ypXvzDKMikvcr0GynWpmkCCeQcmI8LBe8s0FpjeF6tjgEvs0wFAYcgzv7c/8q0lcwWWroHhdcnSRPvWxGcr8kcu7FSWkIlJazAWgOoMDDQnyOknb1puRxNmZq7XAXlZPLH4t9IdIJE0hVU/ibvS+rsiREbuIyPju4DrHR9NedQE01hWWWog1gYoYxtuyLuG+5Y/h6UIenfclXarxKT6KGh2zwto9qJCHKfGkOjvf9muBkgS2oaYv5pYQLZnhQOUyAgU89lbnunb1slC+walMy0nsxR+OdfhtAdkEJZejp1u1J6AmVp23UbHZP9CODlX5eaeSJpI/cw==
server:
  priorityClassName: important
  extraArgs:
    - --insecure
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  secret:
    create: false
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
repoServer:
  priorityClassName: important
  env:
    - name: ARGOCD_GPG_ENABLED
      value: 'false'
  containerSecurityContext:
    seccompProfile:
      type: Unconfined
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
controller:
  priorityClassName: important
  resources:
    requests:
      cpu: 50m
      memory: 1Gi
redis:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
applicationSet:
  priorityClassName: important
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
notifications:
  priorityClassName: important
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
