apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whisper
spec:
  hostnames:
    - whisper.int.imdevinc.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: whisper
          namespace: whisper
          port: 9000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  labels:
    app: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
        - image: hwdsl2/whisper-server
          imagePullPolicy: IfNotPresent
          name: whisper
          env:
            - name: WHISPER_PORT
              value: "9000"
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data-hp
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"
      volumes:
        - name: data-hp
          persistentVolumeClaim:
            claimName: whisper-server-data
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  labels:
    app: whisper
spec:
  selector:
    app: whisper
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-server-data
  labels:
    app: whisper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: hostpath-csi
