apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: shelfmark
spec:
  target:
    service: shelfmark
    port: 8084
  rules:
    - hosts:
        - shelfmark.int.imdevinc.com
  scalingMetric:
    concurrency:
      targetValue: 10000