# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nfs-pv
#   labels:
#     name: mynfs
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     server: k8s
#     path: /mnt/media/nginx
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  annotations:
    nfs.io/storage-path: test-nginx
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nfs-test
          persistentVolumeClaim:
            claimName: nfs-pvc
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: nfs-test
              mountPath: /usr/share/nginx/html