apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dropmind
resources:
  - namespace.yaml
  - sealed.yaml
  - service.yaml
images:
  - name: ghcr.io/imdevinc/dropmind
    newTag: 0.1.1
replicas:
  - name: dropmind
    count: 0
