---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dropmind-secrets
  namespace: dropmind
spec:
  encryptedData:
    DROPMIND_COOKIE_SECRET: AgASap8gp1wzMzKYIUbdZqnSfkTkDwZIGD+N+hWmzbE1+BshJdg8HXxu7zTkAEjUoU9/zwEsy8EdRayM9Inyg0M1JbXHZRx+PyQhbRlMIFewXhqNJEFqv1Fzv4mAhgkVaD93yOQiaB81U45xTdNXu5C8owotgkWc+kufQ2V7/uPX0iWfWoAZEzkIUytuvhJlap0F/pAw2m9iuJ9Bn3spFrP2badK1EDYqBe8PT7jvkNt2meGUT3pGVtjmajCdPmGoqM6dyfKXa0DS9ETyEKsALo871ZtqnJ8CCxeyroD3b9W5qd1vVoCcWfv9Kye1CGE/2snHzPOa5jsxSWSpfXVUrsg1cVIzECu5/sCO/AGdZUdg0walli0hdQifnZhT8G7tZEVesjzlCG+5rNovAOhuHzqJs5rY+iY8W9/PnVqP/8Ja+AflAPMGN9UQo/W5g8d/wbiXqgyYVGUbrx2H4eVcUb65YSj5hAbFZ0BwSlPSaufDyXloJPaplHwYfEXOuLLNZUeqrQMZ9qx7E3MEDVosesDJ3jg2TTnqjWZCao3zSS4QRe1xpYj6J3eeeaSjwv9vSrc8uvn8BmtktGsOyivBsCdgYYdWHFXSUek7oZe/ZLBHOoR5z1UXNo+CZQhQVUumQ4pW5VwLAwSQFNR6J0F5TafHkf5cDfX1lxSD5yFARu6mRFcTBMMvR7KBB4dmM6duDIBqFO8Cj+GGAK5KyLsclLoI/BNcuUoure19AI=
    DROPMIND_TOKEN: AgCFl9hj5uDCHGgWjIR3tuWPuVcdoB1okhxYpIUGkEwZcOetfZbhVYXgLDDU/uLNgx4+IhTUaHog2S82p11GBYoUJs8kda8sQasnJGgHS8xgnzBzMxq9zhb3qpsSnbN13C/D3f94J2IPTxDvJi9+m0Q83ZeG+RExBPQHdxx7rcWvmY4RG1fb5mIa55ZpwYXuXRITyjrgEBzXf4zYo5fJoVLgWdK4VKEvi3T2bneZVPu9W533DfOWrKvcpuuN5vwD9JQevUoGvglL7S7q+2gEd0+gF5h4hJFTS8zR3KJlYZJ7HZOzMGG+6p8EzxsjJ12RqjUYSqvRqYHsg/W5keR/uBn2BPGbIQI43ETF3wjbNX5YaJvfn6B6FBJ+YgeANxVPvXMMy2th91XQ0JpvINlVTLIvxWsbXfoIoOme8WvqkbTVJNQjelmjIqmTe/W0PjLRPFPe6a3P027UUZbaKe/bEfJDgH6Pastg1mU0v9vP4l0EBnS/aZnnQFOMfoI6ds8Ddb2g8JrD5/wpQ6/N2l1CZiVBCaPJjYNZ+0YL+lEiU9FY+tXl8Mt17f2q7pb8igu1/Dw6jH8MGFDQtguO/0zEbBsJMwhTSvMCG4ge4mRYBflbDbje7ChXmAROKFGj3kGuaIVb5t6VlH+HwVvgySo3idFcr3/RDu4SzeBpGpLVF6pLMqu8btIeHlPD1ccwRA+nOf0++y9u6OWpzL0=
  template:
    metadata:
      name: dropmind-secrets
      namespace: dropmind
