apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-creds
  namespace: postgres
spec:
  encryptedData:
    pgpass: AgCQc8Xv6BU4SNvWn5Dkew2/MwE0+v60DUB74U1NJyUnYQMxvoHGk+A6748Mpgw1gcDlTHftGLo3morEFSeLqKlNPYbEhkHc/gy9xJo6ioOBvC9pHsljD+kW/euU64FV3iKNRDjGP/im2P26jUkTtKXemFZ0QZGwf43TZCFjTXigFxJcB6S2SVdgjWhPM6DzbxHzqjILYUMNcGHcVZmEH3Xu0k9UskyvwWw1hgnyWhw6HvObjXiXXxZtO4Bbk9yrZNZZqRWkhXQ8d5bUUbZwpN2Ng7gI6aK5artkczz4I+7GvCCQ35q9f5tVMnDi6OYXW2KlvnmixCE3oulCY5jSlvBANMh+saq+d9dD1qAESmT5tD/TdWowaO3/EXmiZlK5ACXpJwxPWdvj/fM0Ru8oWGdR9/++KGfL9PWYoMmxSHdTc/memu6CDvbAWOEA79aiCFdv7IZrNFXd2xNBZ5IXQuAdy5yxIqd2+zfEBW3dgTxM/8pOJDSLS+WgmLREnyGLMJqGZ5vUKQsG4TR9R/y0ZYZ0QkAg8UVuKzpPDuy7IiERafq51qqEeibv0DeMf54DhepaW1jNRDC21rrCJ76AzU2b9GCteje4XH4PW4+BJZQsBuqGc+E4Gb9IHLPdhkmIrgyZBz0xGyMIZzGcXGQckGwdUfM08p5Glfk6a/Kq/2jFwffWWa48+yWWUfVuVCBVoUmeF67PemdrQtsXlyzhdTZck9TLWrLSXA==
    pguser: AgA7Gm4ypv0nmMPx+v3JLJD5NKrWCYfpOv2LWZyfPPXOL5p/ej7sXi2WLsJlddyMLJLDKZDFn4IORxQT54HZJHRMRY0xCxk9itZ8mLDUb/dl6shdFvHqEnDAyJVyiN1PNqX2+g2va2mGuNp9AIdkpNw0tGRc1Ai3yzuMB/zIhh7Lf6TuZ+tSPjsXYKFIdY1jAEdIGWkxwYOkXNZ0BJClr0/bI2umrTbmgfgLFcxBIFYKH8DRlXZ2d35RBe9zfEHlip6nkuHNU3h+SdJ0ogIcFGVash7zUOJmSLHcpw1S/ALL7cGXEwaMHbj7/+vfG6r2YaKtGLKFmJkV+WwHEsD5bUkSdO+wWbPFqeajporbMzrHtmk4f08M3I27nncZMSvy/haL/Iof2EiRLpjSwWsN4nxycSrB35V4GxfJ5HCWiP2V2ib2mVwT7e5U49Bb/0l26/SsX4j2G/GV0ZZ0qrDNBqvsk6dbEKaiGqds63i8c6puBMCdgB+ANynDK2CmxzizBr8jsbWc/yB4Ow/hXmXvgmYcKg3OX4SUm++HU3Hr1AOQRDwoZ+D2+3anFXnbLajDdVCvslk5/kFi0pDil7nwgtFrOV89hCXYpqaRoKM1I0o2mHptPNQMZMmdFd70Cmy8DANLD1HVUmD5D0K+fKsdFYNPJo2hOwyWAZDMZ5QfMcqTRJx86h9TYNqy2MZweYbawRYFv33GIP9q8w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-creds
      namespace: postgres
    type: Opaque
