apiVersion: apps/v1
kind: Deployment
metadata:
  name: legoai
  labels:
    app: legoai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legoai
  template:
    metadata:
      labels:
        app: legoai
    spec:
      containers:
        - image: ghcr.io/imdevinc/lego-ai
          imagePullPolicy: IfNotPresent
          name: legoai
          env:
            - name: LEGOAI_IMAGE_MODEL
              value: "google/gemini-3.1-flash-image"
            - name: LEGOAI_CHAT_MODEL
              value: "google/gemini-3.1-flash-image"
            - name: LEGOAI_OPENAI_BASE_URL
              value: "https://openrouter.ai/api/v1/"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: legoai
  labels:
    app: legoai
spec:
  selector:
    app: legoai
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
