apiVersion: v1
kind: Service
metadata:
  labels:
    service: redisinsight
  name: redisinsight
spec:
  ports:
  - name: http
    port: 5540
    protocol: TCP
    targetPort: 5540
  selector:
    service: redisinsight
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redisinsight
spec:
  hostnames:
  - redisinsight.int.imdevinc.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: traefik-gateway
    namespace: traefik
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: redisinsight
      namespace: redis
      port: 5540
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redisinsight
    service: redisinsight
  name: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redisinsight
      service: redisinsight
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redisinsight
        service: redisinsight
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - env:
        - name: RI_REDIS_HOST
          value: redis-master.redis
        envFrom:
        - secretRef:
            name: insights
        image: redis/redisinsight:latest
        imagePullPolicy: IfNotPresent
        name: redisinsight
        ports:
        - containerPort: 5540
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: insights-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insights-data
  labels:
    service: redisinsight
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insights
  namespace: redis
spec:
  encryptedData:
    RI_ENCRYPTION_KEY: AgAIqI3V4A7Za3vom1hQoYFJrpwR0x900WU/jkC/QgqtiQBWBz599M3uVIBb1wAIFtxb9c/sL/hTmwJeAMPtZn9A3EUbnVtKG4PZ6qwSa/HrxKYCS116S27PucOgqFFQQiauRIp+3wdhMiw+cHGzUgzWuy7J0F3pv4LI2KBl2JaeHovdpuDCVX6ytYMSKfYVQmHC4X42Sesm3OIxGWRx3jQEDgzsGlcdvRhmWx1/kgeG6SW2v1pugjGp8nRHeqaUacSiPtWx9ySYzkmfvzgui+9igzMx/4smID0MPLL8Jl6aPv6bsRUEXUpw4Qenqr0Gc5iV5WXGE8kpHM13ks6SCLLARWcX+cFrtmm7+gKbj+XksRq+ZlIEHQ9pyl8VK5I8OqCQUv5IitA9bc6nwCGyQs6Pg95meR5jNst+Z1qfdmo6sxqqJU4Ie5B1yGjC1wqn8oR9oq+MDs3EOv/Px/GVhARlWEtJJ7/JiRp+J5T4ddgMRXbLzodyU0mG+9QWPEuPlYts8UNPvi/XAsp4pd7aCSR8Fvx7Z/JcfrBC4Q4mzXPOoUspom88IG+qwMVGuQvyYh6LF2O/0ZsDlWQdDKZ4dWwaWT90I+Sxt3WFqgORI0Efbkyaa6e8WIyC+uiLrxjEB93UyD1j6HY2Z443xwPWsNtR58TqTy1H1Ym3SMPYYOBr+cPHyNj0Blnp3aDBgtWxeE0/EfDP7gGSnAd95vQc0tsTqr7rNGxtcASpD0A2/k5Qbb9D3MYco59lRkWeZw==
  template:
    metadata:
      name: insights
      namespace: redis
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: insight-oidc
spec:
  plugin:
    traefik-oidc-auth:
      Provider:
        ClientId: urn:k8s:secret:insight-oidc:CLIENT_ID
        ClientSecret: urn:k8s:secret:insight-oidc:CLIENT_SECRET
        TokenValidation: IdToken
        Url: https://login.int.imdevinc.com
      Scopes:
        - openid
        - profile
        - email
      Secret: PMYZT3D2J4da20RsSIMMZaArKI6d3pxt
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insight-oidc
  namespace: redis
spec:
  encryptedData:
    CLIENT_ID: AgCC65t2kCQ4hNbIq3SPu4bCqBTo+5xHwVaYcBvOV4RELu01BUdqhK9eJLHF+ILZEpG0lWO8jQesmt45iGZCHdojQjbOm09GnGq1gW3IkUolyifRBXBr8cyMd6yoSUXfW3nlIpGtEvCtX52OD9YRYJRCWKQ0ATPwTHK8cfs14fz7p2qDHExuLFHjhZ0O1SPuqPPOUJDaPCbOB4ROk26GiwRJgOsId6xFi/9KYZATOS+722V43uke8xbx6j8BwEbEEjx9pra59uGS/mxMbrg/8UTqqpJ6aBlURcYLW5chMZeCKRN2h/dgTqjh6zRyscUOsGEkJ11w+7nBVn6NjPYH2CGqLEMWgY2H/SvIjQZ62UchZLeRrbnapM7aZ0QJKktQSUTyJGhDwD39u2HjpkNoc9dGVKZZ1gYCHBdc+jV64EXJTNHEidyDBeLpOa1hCty9ktfxvC2kJ6WNwJ6WfVIbPH7hlWbPw+gcTc1Y1R0NGUZTA9thAJBQ+wZwL4NB2cwrGgzo6bf9E/O8FLfG6eNJBMVew+3m2aV4WzlT1KS3jHDKqgl1f5XQBbBWleekVFXpQkEmEVVm4UFHs5PcEil8Qa8cDjXuxZP6SuI+nwMbMoDcMf4h/CGX7DAGNTw+1Ra41swPAho6UC+nsBzE9H1Z6vKp0A7X4AMAJzL2YC8FIqM8nNSnC96LOQ9DGTxIK2XmVHd1Pp1+rZXAlFZjgsPtsC+E9nY1YygfG9sJztIYh2AWL5yeSJI=
    CLIENT_SECRET: AgCABIbOZMk0b3XHm+RWvzFQSWrUSkymGGH6Qq+zBPiBOzyBe7rFypNlXgw91EgCqs/sK2ChY6hepL00OshdV1AY8U4jDMk9BBv80TN4LYuQTQAlqOiXcvxGmqNb+3FHzn+WsmUJs6vyIrlcc3chHu1620Zag3jDdPB37I3Ns6qwcOpTys2NDKroBNm+lckUMGQBRKDk9an6wrgMrHx+S08E+SlwrOaAxZQ4XUxtFwel+Srph5NjrOd3nJI+5+8bQXhGJm/wCc2/NQZN+HGq6LmnMA3qQMhJXUw9pQ+NyfST/2lIjwJ8ok7mN6D72BzQkUqW01ak3/R4ujh2FbYUoRlQM7ANpAHdY2qyF3PpOvYg81YiN+oUxWG3/6T1n6xyso6S4OuA6ogyzQEv7bW7KPqJX3keR2GCM1CIp07nY32sJqN3q02c88J/H88a/62jbeprDMxiG8ZNeCWkEauB6OF0r8UGX/Wk3Lvhx8/Mp8PMlLjwvdBCs8yKV/LA8EFuR0eOuqiPfAVLpLL0zZwgA/JeHEZq/xQrm29v24QoNOnC1Y/b/VicOIYAYmdvtVSUA58ztFvrmeqMTB7lBKIXN3rSGN/gvTNzLyDNVlHbw2wAfsn20XHKu86x7bfpMt5cbX5YTm62FquZ5LNYBJXfXcVBuqN3dFvA6rBIv+wIOg1rBcquqkbWvjmRTLhGlG+9eSC/Y2UZwTOFnJd/NwIe/i0jp1FfiGFd0e+zsPJ7VxEZUQ==
  template:
    metadata:
      name: insight-oidc
      namespace: redis
